/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as BrevianApi from "..";
export declare class ForbiddenError extends errors.BrevianApiError {
    constructor(body: BrevianApi.ForbiddenErrorBody);
}
