/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as BrevianApi from "..";

export class InternalServerError extends errors.BrevianApiError {
    constructor(body: BrevianApi.InternalServerErrorBody) {
        super({
            message: "InternalServerError",
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, InternalServerError.prototype);
    }
}
