/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as BrevianApi from "..";
export declare class TooManyRequestsError extends errors.BrevianApiError {
    constructor(body: BrevianApi.TooManyRequestsErrorBody);
}
