"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BrevianApiTimeoutError = void 0;
class BrevianApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, BrevianApiTimeoutError.prototype);
    }
}
exports.BrevianApiTimeoutError = BrevianApiTimeoutError;
