/**
 * BREVIAN API
 * API Interface for interacting with BREVIAN AI Platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostChat200ResponseChoicesInner } from './postChat200ResponseChoicesInner';
import { PostChat200ResponseUsage } from './postChat200ResponseUsage';

export class ChatResponse {
    'id': string;
    'conversationId': string;
    'created': string;
    'model': string;
    'choices': Array<PostChat200ResponseChoicesInner>;
    'usage': PostChat200ResponseUsage;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "conversationId",
            "baseName": "conversationId",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string"
        },
        {
            "name": "choices",
            "baseName": "choices",
            "type": "Array<PostChat200ResponseChoicesInner>"
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "PostChat200ResponseUsage"
        }    ];

    static getAttributeTypeMap() {
        return ChatResponse.attributeTypeMap;
    }
}

