/**
 * BREVIAN API
 * API Interface for interacting with BREVIAN AI Platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostChatRequestMessagesInner } from './postChatRequestMessagesInner';

export class Choice {
    'index': number;
    'finishReason': string;
    'message': PostChatRequestMessagesInner;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number"
        },
        {
            "name": "finishReason",
            "baseName": "finish_reason",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "PostChatRequestMessagesInner"
        }    ];

    static getAttributeTypeMap() {
        return Choice.attributeTypeMap;
    }
}

