/**
 * BREVIAN API
 * API Interface for interacting with BREVIAN AI Platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Usage {
    'promptTokens': number;
    'completionTokens': number;
    'totalTokens': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "promptTokens",
            "baseName": "promptTokens",
            "type": "number"
        },
        {
            "name": "completionTokens",
            "baseName": "completionTokens",
            "type": "number"
        },
        {
            "name": "totalTokens",
            "baseName": "totalTokens",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Usage.attributeTypeMap;
    }
}

