/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../..";
import * as BrevianApi from "../../../api";
import * as core from "../../../core";
export declare const PostChatRequest: core.serialization.Schema<serializers.PostChatRequest.Raw, BrevianApi.PostChatRequest>;
export declare namespace PostChatRequest {
    interface Raw {
        messages: serializers.PostChatRequestMessagesItem.Raw[];
        agentId?: string | null;
    }
}
