/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrevianApi from "..";

export interface ChatResponseChoicesItemMessage {
    role: BrevianApi.ChatResponseChoicesItemMessageRole;
    content: string;
}
