/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BrevianApi from "..";
export interface ChatResponseChoicesItem {
    index: number;
    finishReason: string;
    message: BrevianApi.ChatResponseChoicesItemMessage;
}
