/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type ChatResponseChoicesItemMessageRole = "user" | "assistant";
export declare const ChatResponseChoicesItemMessageRole: {
    readonly User: "user";
    readonly Assistant: "assistant";
};
