/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BrevianApi from "..";
export interface ChatResponse {
    id: string;
    conversationId: string;
    created: string;
    model: string;
    choices: BrevianApi.ChatResponseChoicesItem[];
    usage: BrevianApi.ChatResponseUsage;
}
