/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrevianApi from "..";

export interface ChatRequest {
    messages: BrevianApi.ChatRequestMessagesItem[];
    agentId?: string;
}
