/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type ChatRequestMessagesItemRole = "user" | "assistant";
export declare const ChatRequestMessagesItemRole: {
    readonly User: "user";
    readonly Assistant: "assistant";
};
