/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChatResponseChoicesItemMessageRole = "user" | "assistant";

export const ChatResponseChoicesItemMessageRole = {
    User: "user",
    Assistant: "assistant",
} as const;
