/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChatRequestMessagesItemRole = "user" | "assistant";

export const ChatRequestMessagesItemRole = {
    User: "user",
    Assistant: "assistant",
} as const;
