/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrevianApi from "..";

export interface Choice {
    index: number;
    finish_reason: string;
    message: BrevianApi.ChoiceMessage;
}
