/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChoiceMessageRole = "user" | "assistant";

export const ChoiceMessageRole = {
    User: "user",
    Assistant: "assistant",
} as const;
