/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type ChoiceMessageRole = "user" | "assistant";
export declare const ChoiceMessageRole: {
    readonly User: "user";
    readonly Assistant: "assistant";
};
