/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageRole = "user" | "assistant";

export const MessageRole = {
    User: "user",
    Assistant: "assistant",
} as const;
