/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageRoleEnum = "user" | "assistant";

export const MessageRoleEnum = {
    User: "user",
    Assistant: "assistant",
} as const;
