/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type MessageRole = "user" | "assistant";
export declare const MessageRole: {
    readonly User: "user";
    readonly Assistant: "assistant";
};
