/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type MessageRoleEnum = "user" | "assistant";
export declare const MessageRoleEnum: {
    readonly User: "user";
    readonly Assistant: "assistant";
};
