/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type PostChatRequestMessagesItemRole = "user" | "assistant";
export declare const PostChatRequestMessagesItemRole: {
    readonly User: "user";
    readonly Assistant: "assistant";
};
