/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrevianApi from "..";

export interface PostChatResponseChoicesItem {
    index: number;
    finish_reason: string;
    message: BrevianApi.PostChatResponseChoicesItemMessage;
}
