/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrevianApi from "..";

export interface PostChatResponse {
    id: string;
    conversationId: string;
    created: string;
    model: string;
    choices: BrevianApi.PostChatResponseChoicesItem[];
    usage: BrevianApi.PostChatResponseUsage;
}
