/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BrevianApi from "..";
export interface PostChatResponseChoicesItemMessage {
    role: BrevianApi.PostChatResponseChoicesItemMessageRole;
    content: string;
}
