/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type PostChatResponseChoicesItemMessageRole = "user" | "assistant";
export declare const PostChatResponseChoicesItemMessageRole: {
    readonly User: "user";
    readonly Assistant: "assistant";
};
