/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostChatResponseChoicesItemMessageRole = "user" | "assistant";

export const PostChatResponseChoicesItemMessageRole = {
    User: "user",
    Assistant: "assistant",
} as const;
