/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrevianApi from "..";

export interface PostChatRequestMessagesItem {
    role: BrevianApi.PostChatRequestMessagesItemRole;
    content: string;
}
