/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrevianApi from "..";

export interface SubQueryMetadata {
    message_id?: string;
    conversation_id?: string;
    sub_question?: string;
    retrieval_type?: string;
    sub_answer?: string;
    citations?: BrevianApi.UnifiedCitation[];
}
