/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UnifiedCitation {
    structured_response?: Record<string, unknown>;
    sql_query?: string;
    type?: string;
    url?: string;
    source_index?: number;
    name?: string;
    page_content?: string;
}
