/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BrevianApi from "../..";
/**
 * @example
 *     {
 *         messages: [{
 *                 role: BrevianApi.PostChatRequestMessagesItemRole.User,
 *                 content: "content"
 *             }]
 *     }
 */
export interface PostChatRequest {
    messages: BrevianApi.PostChatRequestMessagesItem[];
    agentId?: string;
}
