/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChatResponseChoicesItem: core.serialization.ObjectSchema<serializers.ChatResponseChoicesItem.Raw, BrevianApi.ChatResponseChoicesItem>;
export declare namespace ChatResponseChoicesItem {
    interface Raw {
        index: number;
        finish_reason: string;
        message: serializers.ChatResponseChoicesItemMessage.Raw;
    }
}
