/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChatResponseChoicesItemMessageRole: core.serialization.Schema<serializers.ChatResponseChoicesItemMessageRole.Raw, BrevianApi.ChatResponseChoicesItemMessageRole>;
export declare namespace ChatResponseChoicesItemMessageRole {
    type Raw = "user" | "assistant";
}
