/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChatResponse: core.serialization.ObjectSchema<serializers.ChatResponse.Raw, BrevianApi.ChatResponse>;
export declare namespace ChatResponse {
    interface Raw {
        id: string;
        conversationId: string;
        created: string;
        model: string;
        choices: serializers.ChatResponseChoicesItem.Raw[];
        usage: serializers.ChatResponseUsage.Raw;
    }
}
