/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChatResponseChoicesItemMessage: core.serialization.ObjectSchema<serializers.ChatResponseChoicesItemMessage.Raw, BrevianApi.ChatResponseChoicesItemMessage>;
export declare namespace ChatResponseChoicesItemMessage {
    interface Raw {
        role: serializers.ChatResponseChoicesItemMessageRole.Raw;
        content: string;
    }
}
