/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChatRequestMessagesItem: core.serialization.ObjectSchema<serializers.ChatRequestMessagesItem.Raw, BrevianApi.ChatRequestMessagesItem>;
export declare namespace ChatRequestMessagesItem {
    interface Raw {
        role: serializers.ChatRequestMessagesItemRole.Raw;
        content: string;
    }
}
