/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChatRequest: core.serialization.ObjectSchema<serializers.ChatRequest.Raw, BrevianApi.ChatRequest>;
export declare namespace ChatRequest {
    interface Raw {
        messages: serializers.ChatRequestMessagesItem.Raw[];
        agentId?: string | null;
    }
}
