/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChatRequestMessagesItemRole: core.serialization.Schema<serializers.ChatRequestMessagesItemRole.Raw, BrevianApi.ChatRequestMessagesItemRole>;
export declare namespace ChatRequestMessagesItemRole {
    type Raw = "user" | "assistant";
}
