/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChatResponseUsage: core.serialization.ObjectSchema<serializers.ChatResponseUsage.Raw, BrevianApi.ChatResponseUsage>;
export declare namespace ChatResponseUsage {
    interface Raw {
        promptTokens: number;
        completionTokens: number;
        totalTokens: number;
    }
}
