/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const Choice: core.serialization.ObjectSchema<serializers.Choice.Raw, BrevianApi.Choice>;
export declare namespace Choice {
    interface Raw {
        index: number;
        finish_reason: string;
        message: serializers.ChoiceMessage.Raw;
    }
}
