/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChoiceMessageRole: core.serialization.Schema<serializers.ChoiceMessageRole.Raw, BrevianApi.ChoiceMessageRole>;
export declare namespace ChoiceMessageRole {
    type Raw = "user" | "assistant";
}
