/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ChoiceMessage: core.serialization.ObjectSchema<serializers.ChoiceMessage.Raw, BrevianApi.ChoiceMessage>;
export declare namespace ChoiceMessage {
    interface Raw {
        role: serializers.ChoiceMessageRole.Raw;
        content: string;
    }
}
