/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const ForbiddenErrorBody: core.serialization.ObjectSchema<serializers.ForbiddenErrorBody.Raw, BrevianApi.ForbiddenErrorBody>;
export declare namespace ForbiddenErrorBody {
    interface Raw {
        error: string;
        path?: string | null;
        status?: number | null;
    }
}
