/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const InternalServerErrorBody: core.serialization.ObjectSchema<serializers.InternalServerErrorBody.Raw, BrevianApi.InternalServerErrorBody>;
export declare namespace InternalServerErrorBody {
    interface Raw {
        error: string;
        path?: string | null;
        status?: number | null;
    }
}
