/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const MessageRoleEnum: core.serialization.Schema<serializers.MessageRoleEnum.Raw, BrevianApi.MessageRoleEnum>;
export declare namespace MessageRoleEnum {
    type Raw = "user" | "assistant";
}
