/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const Message: core.serialization.ObjectSchema<serializers.Message.Raw, BrevianApi.Message>;
export declare namespace Message {
    interface Raw {
        role: serializers.MessageRole.Raw;
        content: string;
    }
}
