/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const MessageRole: core.serialization.Schema<serializers.MessageRole.Raw, BrevianApi.MessageRole>;
export declare namespace MessageRole {
    type Raw = "user" | "assistant";
}
