/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const PostChatResponse: core.serialization.ObjectSchema<serializers.PostChatResponse.Raw, BrevianApi.PostChatResponse>;
export declare namespace PostChatResponse {
    interface Raw {
        id: string;
        conversationId: string;
        created: string;
        model: string;
        choices: serializers.PostChatResponseChoicesItem.Raw[];
        usage: serializers.PostChatResponseUsage.Raw;
    }
}
