/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const PostChatResponseChoicesItemMessage: core.serialization.ObjectSchema<serializers.PostChatResponseChoicesItemMessage.Raw, BrevianApi.PostChatResponseChoicesItemMessage>;
export declare namespace PostChatResponseChoicesItemMessage {
    interface Raw {
        role: serializers.PostChatResponseChoicesItemMessageRole.Raw;
        content: string;
    }
}
