/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const PostChatResponseChoicesItemMessageRole: core.serialization.Schema<serializers.PostChatResponseChoicesItemMessageRole.Raw, BrevianApi.PostChatResponseChoicesItemMessageRole>;
export declare namespace PostChatResponseChoicesItemMessageRole {
    type Raw = "user" | "assistant";
}
