/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const PostChatResponseChoicesItem: core.serialization.ObjectSchema<serializers.PostChatResponseChoicesItem.Raw, BrevianApi.PostChatResponseChoicesItem>;
export declare namespace PostChatResponseChoicesItem {
    interface Raw {
        index: number;
        finish_reason: string;
        message: serializers.PostChatResponseChoicesItemMessage.Raw;
    }
}
