/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const PostChatResponseUsage: core.serialization.ObjectSchema<serializers.PostChatResponseUsage.Raw, BrevianApi.PostChatResponseUsage>;
export declare namespace PostChatResponseUsage {
    interface Raw {
        promptTokens: number;
        completionTokens: number;
        totalTokens: number;
    }
}
