/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const PostChatRequestMessagesItem: core.serialization.ObjectSchema<serializers.PostChatRequestMessagesItem.Raw, BrevianApi.PostChatRequestMessagesItem>;
export declare namespace PostChatRequestMessagesItem {
    interface Raw {
        role: serializers.PostChatRequestMessagesItemRole.Raw;
        content: string;
    }
}
