/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const TooManyRequestsErrorBody: core.serialization.ObjectSchema<serializers.TooManyRequestsErrorBody.Raw, BrevianApi.TooManyRequestsErrorBody>;
export declare namespace TooManyRequestsErrorBody {
    interface Raw {
        error: string;
        path?: string | null;
        status?: number | null;
    }
}
