/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as BrevianApi from "../../api";
import * as core from "../../core";
export declare const Usage: core.serialization.ObjectSchema<serializers.Usage.Raw, BrevianApi.Usage>;
export declare namespace Usage {
    interface Raw {
        promptTokens: number;
        completionTokens: number;
        totalTokens: number;
    }
}
