"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.BrevianApiClient = void 0;
const core = __importStar(require("./core"));
const BrevianApi = __importStar(require("./api"));
const url_join_1 = __importDefault(require("url-join"));
const errors = __importStar(require("./errors"));
class BrevianApiClient {
    _options;
    constructor(_options) {
        this._options = _options;
    }
    /**
     * @throws {@link BrevianApi.ForbiddenError}
     * @throws {@link BrevianApi.TooManyRequestsError}
     * @throws {@link BrevianApi.InternalServerError}
     *
     * @example
     *     await brevianApi.postChat({
     *         messages: [{
     *                 role: BrevianApi.PostChatRequestMessagesItemRole.User,
     *                 content: "content"
     *             }]
     *     })
     */
    async postChat(request, requestOptions) {
        const _response = await core.fetcher({
            url: (0, url_join_1.default)(await core.Supplier.get(this._options.environment), "chat"),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
            },
            contentType: "application/json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : undefined,
            maxRetries: requestOptions?.maxRetries,
        });
        if (_response.ok) {
            return _response.body;
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new BrevianApi.ForbiddenError(_response.error.body);
                case 429:
                    throw new BrevianApi.TooManyRequestsError(_response.error.body);
                case 500:
                    throw new BrevianApi.InternalServerError(_response.error.body);
                default:
                    throw new errors.BrevianApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }
        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrevianApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.BrevianApiTimeoutError();
            case "unknown":
                throw new errors.BrevianApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
    async _getAuthorizationHeader() {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
exports.BrevianApiClient = BrevianApiClient;
